### ISSUE TITLE
How can i erase this chip and flash my own program

### ISSUE THREAD

**Issue by kaidegit** [KitronikLtd/kitronik-arcade-uf2-bootloader#3]
it seems that the atsamd51j19 chip on this kitronik arcade board is in secure mode. I try to use segger jflash to connect it and it says i should earse it to unsecure it. I clicked the yes and it circularly show  `Mass erase done!` 

i also try to use openocd to connect it. I tried to connect it with `C:\openocd\bin\openocd -f "interface/jlink.cfg" -c "transport select swd" -f "target/atsame5x.cfg"` and it shows that 
```shell
xPack OpenOCD, x86_64 Open On-Chip Debugger 0.11.0-00155-ge392e485e (2021-03-15-16:44)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
swd
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : J-Link V9 compiled May  7 2021 16:26:12
Info : Hardware version: 9.70
Info : VTarget = 3.349 V
Info : clock speed 2000 kHz
Error: Error connecting DP: cannot read IDR
```

it seems that i cannot connect it with gdb and cannot run the cammand in readme/fuses. 

can you give me some other method to earse this chip and flash my own program? thanks a lot.

**Comment by DaveAtKitronik** [comment]
The boards should not ship from here with the secure bit set, I will check with production about that. Both boards Ive looked at today do not have it set.
The board can be reflashed using a UF2 update file, via USB. 
Some details here: https://makecode.com/blog/one-chip-to-flash-them-all and here: https://github.com/microsoft/uf2
The UF2 updater will set the boot loader protection fuse to 16Kb - to prevent overwriting of the boot loader.
I am using Atmel Studio to drive a jlink - so I can unset the fuse directly. I thinkit can be unsed with the GDB command:
set ((Nvmctrl *)0x41004000UL)->CTRLB.reg = (0xA5 << 8) | 0x1a

**Comment by DaveAtKitronik** [comment]
@kaidegit  - Did this solve your problem?

**Comment by kaidegit** [comment]
hi there,
    i am so sorry that i am preparing a competition called National Undergraduate Electronics Design Contest（全国大学生电子设计竞赛 in Chinese) so i now have little time to test it. I will test it after it. thanks for your solution !

**Comment by DaveAtKitronik** [comment]
No problem. I will close this now and if it still does not work please open a new issue.
Good luck in the competition.
